name: example
description: An example app.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.0.0
dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  progress_animation_builder:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true