name: progress_animation_builder
description: ProgressAnimationBuilder
version: 1.0.0
author: Masayuki Ono <mono0926@gmail.com>
homepage: https://github.com/mono0926/progress_animation_builder
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: